server:
  port: 8080

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

WELCOME_MESSAGE: hello
PORT: 8088
MEMORY_LIMIT: 256
CF_INSTANCE_INDEX: 1
CF_INSTANCE_ADDR: 10.10.10.000
